spring.application.name=patent-api
server.port=8080

external.serp-api.key=${SERP_API_KEY:}
external.serp-api.base-url=${SERP_API_BASE_URL:https://serpapi.com}
external.deepl.key=${DEEPL_API_KEY:}
external.deepl.base-url=${DEEPL_API_BASE_URL:https://api-free.deepl.com}

logging.level.com.jjs.patentapi=DEBUG

management.endpoints.web.exposure.include=health,info
