spring.application.name=patent-api
server.port=8080

external.serp-api.key=${SERP_API_KEY:}
external.deepl.key=${DEEPL_API_KEY:}

logging.level.com.jjs.patentapi=DEBUG

management.endpoints.web.exposure.include=health,info
